{% set version = "0.5.1" %}
{% set sha256 = "7532bb4c3b4a083a8438e2f3039bff9cb64174831a30425cb7d8421b9f04f38f" %}
{% set openjdk_version = "8.0.121" %}

package:
  name: scijava-jupyter-kernel
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/scijava/scijava-jupyter-kernel/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32 or linux32]

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
  run:
    - openjdk =={{ openjdk_version }}
    - notebook
    - jupyterlab

test:
  requires:
    - jupyter_client
  commands:
    - conda list scijava-jupyter-kernel

about:
  home: https://github.com/scijava/scijava-jupyter-kernel
  license: Apache
  license_file: LICENSE.txt
  summary: 'A Java kernel for Jupyter.'
  description: A Java kernel for Jupyter.
  dev_url: https://github.com/scijava/scijava-jupyter-kernel
  doc_url: https://imagej.net/Scijava_Jupyter_Kernel

extra:
  recipe-maintainers:
    - hadim
