{% set version = "0.2.4" %}
{% set sha256 = "44171c77f32da3e8514870890f07f6a46fab277d119687735dfab8b2c20d93b4" %}
{% set openjdk_version = "8.0.121" %}

package:
  name: scijava-jupyter-kernel
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/hadim/scijava-jupyter-kernel/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32 or linux32]

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
  run:
    - openjdk =={{ openjdk_version }}
    - notebook
    - jupyterlab

test:
  requires:
    - jupyter_client
  commands:
    - conda list scijava-jupyter-kernel

about:
  home: https://github.com/hadim/scijava-jupyter-kernel
  license: Apache
  license_file: LICENSE
  summary: 'A Java kernel for Jupyter.'
  description: A Java kernel for Jupyter.
  dev_url: https://github.com/hadim/scijava-jupyter-kernel
  doc_url: https://imagej.net/Scijava_Jupyter_Kernel

extra:
  recipe-maintainers:
    - hadim
