travis:
  secure:
    BINSTAR_TOKEN: BUD3UwOJFDdHvT848mdYBvM+rZiki7bUr2w8Wu6Nr3yeFYfgHzcKOH/Ze3CI6WDu5zDWPOKWeETRJ6LxFUD6ZqXwnPtUhrHvZyZIhbCOXfpVw2koogYa+MedPW2Vni/7R/7JyW0feeaEncAaAqu1gjpgSwd+RX/zqGBfLe+ru5J4JUumpbfwB5C4OA1mAXAslsAhByLqIA0HnJ0WGnWQ2l4ZtQwW75xhpz13/RWj1z9jwcQ8HVHDrkB0S/MN/9SIzIt9vpkJJWu+D/EnYvpbGRVJWPkZXzGjCN+ErFMhl7y9qhGduTQA4aJQ7qb0+oh85SNBNQcNFtgcCGN62wUMHnwEHgLmZPHRtC3LfXateBX78AwCgDDsdew7FLzwOkfEuFdItDu3i6+HfCgecB3R0GuenxX8+buGGwaHlwPUj30+0/4zTqRp1Rv6WOenuhsH4YDBp9XBVR0TEdX+IirPYYQuunSt6wOUUvEruzN8WFW6h+tBesKQhd3vnz37pgq1jfGicltKpVRbBOFt42BGXAco0AjLWiHB2oDU3dyWV9PHDvo5gIF3u+HFFtwRVKk8l7lP6MpQ+bRfzLnXaNkKqdwt4ujIWtpruy5pUjb/G6US3Cm4dczjFTLR7tGXaYQa853VApeVYDIuNhySZH4EzoP01oGzRTP5xtJ1OENbwTU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
