travis:
  secure:
    BINSTAR_TOKEN: Lx1CzX6zbVTUW41eFxJF/6nY/LhRfYfvfJWi+ixzZ8sa/UCRypOGf1zij20XUvbljNOZ2AHGqFizG8DJdCnOUOeekiE3ZCfag0lklntkXFi0RTUXtUzZxqNQugQ/ruGbOFL2n7otJ70DBV+He8FdEP6a/itvVZVreKO7aRSohUzEZv4npvgiq4p9I/JTBXaRz6D+wGEWjeV4P8XJPV9bpwMH+5R3hnKFXIMRMpmkWv+RxDsYgeEAucGrmv8bGmSXpmC3UoZWtGH8O1HZIeyGky9pnPjft6QzDMlxalpC4W4rqVh4ZdkbR/Wp5wM1q54N4cPQTBJlRNkYhxqWGbwTMBH6xZCusB1bLXEI7s35yGg3LoJKHEyd1RFNsZqTfLHMVsSggMYY2c/gfJH22337e/uy7gL0ds5b3r8ZHi6Xz7v8vVbxBlGu3ne1s0JqeWqzoyMKlj1hstIeRKT/GZxGqpLSCoQZsHjNE2Lf6hpZ253GW0KL5NWE5ZC1wA/ccO1tjv6mNX4DSsBdP/XPk8lX3RvlX8LEhhvCt/0qQPJj6rswB1HKagHdOv66WTGQPFt0LoofZGBdZ2raF4C1mh+s3tFFeVqq0WUpI+ch09XCZPEqsvexPsU4GNheWpkZXe7js75oMrg7/I+edwVPg1uBsEuKGMa5+F7VpccUZJuEY+4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
